### PR TITLE
Check if the loaded script was the one exporting the required value

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey Chema,

This is not that simple as it looks like. I also just realized that what we committed yesterday might not work neither in some situations. Here is why:
Let's assume the user has required three scripts. Depending on `combine` value and the type of the module (if it starts with http or not), the URLBuilder may create three, two or only one URL. So, this [code](https://github.com/jbalsas/liferay-amd-loader/commit/c61188d9256638ec070e30d165a5e0a2f3115e17#diff-e8251939a52be372ecd7aecd39362c6aR472) may not work.
The URLBuilder does not return information in which URL each of these modules went. If we had this information, we could create an array in which we could store the export values and pass this array to `_loadScript` function.

An example:
require(['underscore', 'moduleA', 'moduleB']...)
Now let's imagine all these three modules export value. Underscore is external, but the other two are not.
When invoking [this](https://github.com/liferay/liferay-amd-loader/blob/78d929d47c79d68c4bf45ae1fe61f808f4a72fd7/src/js/script-loader.js#L464) function, The URLBuilder would create two URLs - one for underscore and another one for moduleA and moduleB.

I think to make this working we should modify URLBuilder to return not only an array, but an object - the constructed URLs as it is now and as a value - which modules belong to each URL. Then, for each URL we should create an array, where we could store the exported values from all modules, involved in this URL.

Thanks,

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-amd-loader/compare/10d990c~3...10d990c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Something like [this](https://github.com/liferay/liferay-amd-loader/commit/4a94260aa78f5acf13eb11602664e80a24dea9aa). If it is OK for you - a new version will be released.

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan!

When I first looked at this I thought we might possibly need something like this, but I was hoping we could keep it simpler... you're right of course, and I was only trying without combine so I'm sure we would have ran into issues sooner or later.

I've tested with all these changes in, both with and without combine and this looks to definitely fix the issue. If you can release a new version, I'll update our dependencies asap :relaxed: 

Thanks a lot!!

**Comment by ipeychev** [comment]
[Here](https://github.com/liferay/liferay-amd-loader/releases/tag/v1.4.1) you have it.

Thanks,

**Comment by jbalsas** [comment]
Thanks so much!! PR for portal is already on its way :blush:

**Pull request merged**
