### PR TITLE
fixes for reassign parameters in define

### PR DESCRIPTION
**Pull request by igor-borisov**

### CODE REVIEW

**Comment by igor-borisov** [comment]
In both cases implementation variable will have the same value as dependencies after reassignments
```
function(arg0, arg1, arg2){	  
    arg1 = arguments[0];
    arg2 = arguments[1];
}
```
it is equal to
```
function(arg0, arg1, arg2){	  
    arguments[1] = arguments[0];
    arguments[2] = arguments[1];
}
```
so `arguments[1]` and `arguments[2]` (arg1, arg2) will have value from `arguments[0]`;

So we need to change order of operations to 
```
function(arg0, arg1, arg2){	  
	arg2 = arguments[1];   
	arg1 = arguments[0];   
}
```
or
```
function(arg0, arg1, arg2){	  
	arguments[2] = arguments[1];   
	arguments[1] = arguments[0];   
}
```
After that `arguments[2]` (arg2) will have value from `arguments[1]` (arg1), and `arguments[1]` (arg1) from `arguments[0]` (arg0) as it should be.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
This is true, but only in non-strict mode. In strict mode arguments don't behave in this way. Let me quote [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Making_eval_and_arguments_simpler): "strict mode code doesn't alias properties of arguments objects created within it". The code posted above:
```javascript
function(arg0, arg1, arg2){   
    arg1 = arguments[0];
    arg2 = arguments[1];
}
```
will not reassign `arguments[0]` and `arguments[1]` in strict mode. As you can see, we have strict mode defined for all the code in the Loader. IE < 11 is dead, so we are good to go.

However, I see that this code might be confusing and I have a suggestion for you - could you please modify the code so that `define` will look like this:
```
define: function() {...}
```
Then, we may declare `name, dependencies, implementation, config` as local variables and assign to them the values from `arguments`.

How does that sound for you?

Thanks,

**Comment by igor-borisov** [comment]
Yes it is true about strict mode. And everything is works fine if we turn off js-minification in portal-ext.properties. But it doesn't work when this option is turned on. So I think with small changes we can make it work for both modes.

What do you think?  Thanks

**Comment by ipeychev** [comment]
Are you sure about this? I cannot imagine how this could happen, because the minifier cannot remove the "use strict" statements. Could you check what is the code of the loader after minifying, please?

About the proposed code, it will make the things even more confusing. We cannot rely on moving lines back and forth to fix the things.

**Comment by igor-borisov** [comment]
Yep, I am sure, that is why I have opened this code :)

**Comment by yuchi** [comment]
@igor-borisov Liferay 7 introduced a new configuration to use Google's compressor instead of YUI's. It could solve your specific problem in the meanwhile. It could also expose new issues, but it's worth a try.

**Comment by ipeychev** [comment]
Okay, could you please test with the latest master? The issue should be fixed [here](https://github.com/liferay/liferay-amd-loader/issues/76).

Thanks,

**Comment by ipeychev** [comment]
Fixed in [v1.5.4](https://github.com/liferay/liferay-amd-loader/releases/tag/v1.5.4)

**Comment by igor-borisov** [comment]
Okay thanx a lot :)

**Pull request closed without merging**
