### PR TITLE
Support a new 'exactMatch' flag for maps

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hey @izaera, would it be possible to rename `exact` to `exactMatch`, please? Then, in the configuration it would look like:

```
__CONFIG__.maps = {
    'liferay@1.0.0/package': {
         value: 'liferay@1.0.0/package/index',
         exactMatch: true
    }
}
```

which will be one idea more clear what it does.

Thanks,

**Comment by izaera** [comment]
I pushed generated files by error :-(. I'm going to do a push -force to fix it.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-amd-loader/compare/037de85~1...037de85) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
