### PR TITLE
Add amd property to Loader.define function #95

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hey @julien,

What happened with [pr-96](https://github.com/liferay/liferay-amd-loader/pull/96) that it was closed and with Chema's [recommendation](https://github.com/liferay/liferay-amd-loader/pull/96#pullrequestreview-16339387) too?

**Comment by julien** [comment]
Hi @ipeychev ,

Yes I closed [pr-96](https://github.com/liferay/liferay-amd-loader/pull/96), because the tests were failing with my last change.

**Comment by ipeychev** [comment]
Which test was failing - the one you added, or the existing ones?

In any case, they should pass, otherwise we either have a regression, or the new test was not precise.

In the new PR there is no test, why it was removed? Better add it back and we will fix it if it was failing.

**Comment by julien** [comment]
What was failing with the existing tests was the change I made in the `src/template/script-loader.template`.  I should have seen it, but I launched the tests without having saved the file (I'm sorry about that).

In this PR there are a few lines added to test/script-loader.js that check if the Loader.define.amd property is defined.

**Comment by ipeychev** [comment]
Aha, OK then.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-amd-loader/compare/ac3436d~2...ac3436d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Thanks to you @ipeychev

**Pull request closed without merging**
