### PR TITLE
Fix namespace issues

### LINKED ISSUE #83: Issue when configuring the namespace for the loader
Hi,

When configuring the `namespace` for the `Loader`:

```javascript
var MyNamespace = { foo: 'bar' };

window.__CONFIG__ = {
    namespace: 'MyNamespace'
};
```

- If an object exists with the same name as the name used in the configuration it is replaced by a new object, only containing a `Loader` property (see [here](https://github.com/liferay/liferay-amd-loader/blob/master/src/template/loader-pure.template#L22)).

- The `define` and `require` functions are not "copied" to the custom namespace.

### PR DESCRIPTION
**Pull request by julien**
Fixes #83

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Please do not send autogenerated files as part of pull request. This project does not accept these, the maintainer will build and push them.

**Comment by jbalsas** [comment]
Hey Iliyan, regarding the first comment, this follows what we spec'd in [this comment](https://github.com/liferay/liferay-amd-loader/issues/78#issuecomment-248828096)

We could simplify it, though and just keep it inside `Loader`. For the loader to work properly when globals are hidden, we actually need to expose `require` and `define` inside the calling closure like this:

```javascript
var require = Liferay.require;
var define = Liferay.define;

require(...);
```

so we might as well do this on our own like:

```javascript
var require = Liferay.Loader.require.bind(Liferay.Loader);
var define = Liferay.Loader.define.bind(Liferay.Loader);

require(...)
```

What would you prefer?

**Comment by ipeychev** [comment]
Well, if the code in @julien's commit works for you too, then let's go with it. Does it?

**Comment by jbalsas** [comment]
Hey @ipeychev, I've been talking to @julien (he's been working with us in the Madrid's office for about a month now :D). We sent discovered this when we tried to integrate the new feature in Portal :(

This works for us, but we both agree that maybe it's enough to simply expose the `Loader` behind the namespace. We'll close this PR and resend a new one with only the final changes (and no build files 😉).

After we merge, I can take care of publishing as well if you want.

Thanks!

**Pull request closed without merging**
