### PR TITLE
Use urlMaxLength for clarity

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @ipeychev, this is a possible fix for #62. We've added a test covering both relative and absolute paths. Please, let us know if there's anything else missing.

Once you merge this, I think we should be good to go with a new release ☺️

**Comment by jbalsas** [comment]
BTW, for reference, the default max size for Apache is [LimitRequestLine = 8kb](http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline). This actually includes some extra information other than just the URI. We've seen errors with little more than 4k chars, so, to be safe, maybe we could bump up our default to 3000.

Other option is to set the default here to `Number.Infinity`, and defer to the users to set a value if they consider they need it.

What do you think?

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/liferay-amd-loader/compare/ff4e12b~4...ff4e12b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
