### PR TITLE
Loader.lazy

### PR DESCRIPTION
**Pull request by Robert-Frampton**
This branch implements the `Loader.lazy` method discussed in #157.

```javascript
const fn = Loader.lazy(
	'some-module',
	function(someModule, foo) {
		someModule(foo);
	},
	function(error) {
	}
);

// some-module has not been loaded

fn('foo');

// some-module will now be loaded by Loader.require and the success callback will be invoked.
```

`Loader.lazy` consumes the exact same arguments as `Loader.require`. Because of this, I abstracted the parsing of the arguments from `require` to `_parseRequireArgs` as this resolving needs to happen for both methods.

You'll also notice this pattern being used in multiple places.

```javascript
var args = [];
var i = arguments.length;
while (i--) args[i] = arguments[i];
```

While it is not ideal to have this code duplicated, it is due to optimization issues with calling `Array.prototype.slice.call(arguments);`. By passing `arguments` to another function, the Javascript engine cannot optimize it properly. This is explained [here](http://code.fitness/post/2015/11/javascript-function-arguments-do-not-slice.html) and [here](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments).

If we ever migrate this project to es6 syntax, we can remove this code, as the transpiler will optimize for us.

One question I have is, are there any better names for this method? I'm not necessarily opposed to `lazy`, but some ideas are `requireLazy`, `deferred`, `requireDeferred`...

### CODE REVIEW

**Comment by brunobasto** [comment]
To me, either `lazy` or `deferred`. Leaning towards `lazy` as it's faster to type..

**Comment by izaera** [comment]
Hi guys:

Sorry to disagree 😬. 

The functionality seems perfect to me, but I wouldn't include it in this project for two main reasons:

1. This project is complex enough to deserve keeping it to the bare minimum so that it can be maintained more easily (its only goal should be implementing an AMD loader, IMO).
2. This functionality can be built on top of the loader using it as a black box (no need to hack it inside the loader code).

Reason 1 is clear enough: the less code we have in this project, the better it can be maintained.

Regarding reason 2, it is quite easy to build this method by just calling require() and doing the same in the success callback. More important: if we do it outside this project, we can reuse the functionality with AMD loaders different than this one (remember that the portal allows hiding our loader and using a third party one). IMO, this is a strong indicator that this feature should not go here.

So, I suggest moving the lazy require method to `Liferay` directly, instead of merging it into `Liferay.Loader`. 

Thinking it in depth, we could even create a "loader helper" library with this method and many more that may be useful (it would make sense if we had more methods like this one). Obviously, in this moment, we only have the lazy require method and we don't plan to add any more in the near future, so it would be overengineering in this moment. But, IMO, the possibility of such a library helps to reason about where this method should go too.

What do you think?

**Comment by brunobasto** [comment]
Hey @izaera, it makes sense to me. Thank you

**Comment by yuchi** [comment]
Totally agree.

**Pull request closed without merging**
