### PR TITLE
Reuses `mapModule` adding a map optional param (part II)

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
@jbalsas this is in reply to https://github.com/liferay/liferay-amd-loader/pull/128

**Comment by jbalsas** [comment]
I'm closing this one for now since I think we wanted to do something else we discussed offline... please, reopen if that's not the case :)

**Comment by ipeychev** [comment]
Haha :) 
And better squash these commits - SpaceX are landing vertically rockets on floating drone ships in the middle of the ocean with less :D

**Comment by jbalsas** [comment]
hahaha... but we're doing it in style!!

**Pull request closed without merging**
